### ISSUE TITLE
Notify compile error with Growl(GNTP).

### ISSUE THREAD

**Issue by ponkore** [liquidz/misaki#19]
[Enhancement] 
misaki.server でテンプレートをガシガシいじっているときに、ミスをしてコンパイルエラーになってしまうことがままありますが、その時 Growl 等で通知を出していただけるとありがたいのですが...(ブラウザとEmacsが画面を占領しているので、エラーを起こした時に何度ブラウザを reload しても変更が反映されない、ということがよくあるので...)。

https://gist.github.com/3254119

ちなみに私が使っている Growl 1.4 (AppStore 経由でインストール) ではどうも UDP では繋がらないようで、 clj-growl は使えませんでした。

(あと、上記 gist で使っている clj-gntp の中身はちょっと微妙な感じ(引数の渡し方とか。Javaから呼び出すことを意識している？)なので、独自に再実装したほうがよいのかもしれません。あと、上記 gist は私の Mac でしかテストしていません...)

**Comment by liquidz** [comment]
#17 が完了したら対応します！

ちなみにGrowlでUDPが繋がらない件ですが
設定の「ネットワーク ＞ 受信される通知を聞く、リモートアプリケーション登録を許可」に
チェックを入れても繋がらない状況でしょうか？

**Comment by ponkore** [comment]
![私のところのダイアログ Growl v1.4](https://github.com/ponkore/stepbystep/blob/master/tmp/screenshot2012-08-04-15.39.28.png)
ネットワーク ＞ 受信される通知を聞く、というのがありません...。

対応は例によって全く急ぎませんので、気が向いた時にでもふらっとしていただければありがたいです。
Growl で UDP がつながらない件ですが、公式ドキュメントには特に記述は見当たらなかったのですが、
[ruby-growl ライブラリのドキュメント](http://docs.seattlerb.org/ruby-growl/Growl.html)(のnew の説明のところ)に以下のような記述がありました。

> ‘GNTP’
> 
> ```
> Use GNTP connections. GNTP is supported by Growl 1.3 and newer and by Growl for Windows.
> ```
> 
> ‘UDP’
> 
> ```
> Uses the UDP growl protocol. UDP growl is supported by Growl 1.2 and older.
> ```

なので、いっそのこと GNTP オンリーにしておいたほうが良いのかもしれません。

**Comment by ponkore** [comment]
よく考えたら 1.2 以前もニーズがありそうですね(MacPorts で入るのは 1.1.6 ですし...)。
GNTPオンリーは言いすぎでした、すみません。
ネット上で調べて見る限りでは、UDP版実装のほうが多いような感じです。
(emacs lisp 版 https://github.com/elim/emacs-growl/blob/master/growl.el なんてのもあるし...)

**Comment by liquidz** [comment]
devブランチで対応しましたのでご確認いただけますか？
デフォルトでは通知オフなので _config.clj 内で以下のように指定してください。

``` clojure
{
 :notify? true
 }
```

なおgrowlとのgntp, udp通信についてはmisakiのコアとは別になるので
ひとまず対応優先でclj-gntp, clj-growlを使っています。

**Comment by ponkore** [comment]
devブランチ確認させていただきました。OKです!! 
しかもエラーから回復したら FIXED になるおまけ付き!!!すばらしいです。

ありがとうございます。

**Comment by liquidz** [comment]
ご確認ありがとうございます！
masterにマージしましたのでクローズします。
