### ISSUE TITLE
duplicated declaration in misaki/config.clj

### ISSUE THREAD

**Issue by ponkore** [liquidz/misaki#20]
全く実害はないので全く急ぎませんが、見つけてしまったので一応報告だけさせていただきます。

_site_ の declare が misaki/config.clj の中で重複して存在しています。

https://gist.github.com/3274146

issue#17 の作業が master に反映される頃に治っていればよいかも、です。(治ってなくても当方支障ありませんw)

**Comment by liquidz** [comment]
ご報告ありがとうございます。
siteのdeclareについては #17 の作業に使っている challenge2 ブランチで修正しているので
master 反映時には直る予定です。

コンパイル部分のプラグイン化によって対象のファイルが変わってしまっていますが以下です。
https://github.com/liquidz/misaki/blob/challenge2/src/misaki/compiler/default/config.clj

**Comment by ponkore** [comment]
issue#17 に言及しておきながら、challenge2 ブランチの中身はみてませんでしたw。
上記 config.clj 確認しました。

**Comment by liquidz** [comment]
challenge2ブランチをmasterにマージしたのでクローズします
