### ISSUE TITLE
"*name*" always expanded to <em>name</em> in string.

### ISSUE THREAD

**Issue by ponkore** [liquidz/misaki#21]
どういうことかというと、ブログ中にインラインで (lisp で変数名等でありがちな) ＊name＊ 
(＊は半角)と書くと、html/core.clj 内の parse-emphasized によって [:em name] に置き換えられてしまいます。

markdown の書式上は理にかなっているのですが、lisp や clojure のコードをブログの中で記述
したいときに困ってしまいます(かと言って、良いアイデアが思いつかないので困っています。
エスケープキャラクタなんてものは気持ち悪いし...)。

良い回避方法が無いのであれば、全角＊で逃げるか、適当な関数をでっち上げて画像として \* を
埋め込むとかしますが...。

どうしようもないのであれば、この Issue はクローズしてください。

**Comment by liquidz** [comment]
ご指摘ありがとうございます。
暫定的な対処として思いつくのは以下の方法ですね、、文字列を区切ってしまうので面倒ですが、、

``` clojure
(p "foo " (code *name*) " bar")
```

個人的にしっくりくる方法としては次のことを考えています。

``` clojure
(p "foo `*name*` bar")
;=> 現状では <code class="prettyprint"><em>hello</em></code>
```

この場合に `inline-code` のパースが行われたあとに `emphasized` が無効になるように修正することが
意味合い的にも良いのかなと考えいるのですがいかがでしょうか？

ちなみにgithub flavored markdownも試してみると `*name*` のようにinline-codeが最優先みたいですね。

**Comment by ponkore** [comment]
上記の 

```
(p "foo `*name*` bar")
```

がすっきりしててありがたいです。challenge2 が落ち着いたあとにでも対応いただけたら
ありがたいです。気長に待っておりますｗ

**Comment by liquidz** [comment]
Growlと前後してしまいましたがdevブランチで対応してみたのでご確認いただけますか？

**Comment by ponkore** [comment]
dev ブランチでテストしてみました。オッケーです。対応ありがとうございます。

**Comment by liquidz** [comment]
確認ありがとうございました！masterにマージしたのでクローズします。
