### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by edtsech** [liquidz/misaki#22]
Are there any plans to integrate markdown into Miskaki?

**Comment by liquidz** [comment]
I have no plan to support markdown at present.
But misaki 0.2.0 beta and later supported thrid-party compiler like following.

> misaki compiler using clostache
> https://github.com/liquidz/misaki-clostache

So if you want markdown support, you can develop it.

Document for developing misaki compiler is here.
http://liquidz.github.com/misaki/toc/07-develop-compiler.html

**Comment by edtsech** [comment]
It's just awesome! Thank you very much for your response.

**Comment by kumarshantanu** [comment]
@liquidz Is there a tentative schedule for misaki 0.2.0 / 0.2.1 GA release?

**Comment by liquidz** [comment]
@kumarshantanu misaki 0.2.0 beta is already released! Current version is 0.2.2 beta.
https://github.com/liquidz/misaki/blob/master/project.clj
