### ISSUE TITLE
Compile with multiple compilers

### ISSUE THREAD

**Issue by liquidz** [liquidz/misaki#23]
from @bouzuya

_config.clj

``` clojure
{
 ; other settings
 :compiler ["foo" "bar"]
 }
```
- misaki.serverでは foo, bar がそれぞれ扱う拡張子の両方を監視する
- misaki.serverは拡張子毎にどのコンパイラに処理させるかを判断する
- 1つの拡張子を複数コンパイラが扱う場合には `:compiler` オプションで最初に指定されているコンパイラに処理を回す
  - コンパイル結果が正常終了を示すものであれば、コンパイルはそこで終了。次のコンパイラへは処理を回さない
  - コンパイラのコンパイル結果がスキップ(真偽値でも文字列でもマップでもない)の場合、misaki.serverは次に指定されたコンパイラに処理を回す

**Comment by bouzuya** [comment]
対応をお願いします！

**Comment by liquidz** [comment]
@bouzuya 大変おまたせしました。devブランチで対応しましたのでご確認いただけますか？

**Comment by bouzuya** [comment]
@liquidz ありがとうございます。今晩にでも確認いたします。取り急ぎご連絡まで。

**Comment by liquidz** [comment]
お願いします！ちなみに "copy" というファイルコピー用のコンパイラも用意してあるので、`:compiler ["default" "copy"]`の指定でテンプレート以外のファイルコピーも確認できます。

**Comment by liquidz** [comment]
@bouzuya こちら問題なさそうでしょうか？

**Comment by liquidz** [comment]
Twitterで確認済み( https://twitter.com/bouzuya/status/256999156739104768 )
masterにマージ済みなのでクローズします。
