### ISSUE TITLE
HTML formatting... 

### ISSUE THREAD

**Issue by syntacticsugar** [liquidz/misaki#25]
hi, how do i use  HTML/CSS formatting for entries?  I wanted to bold, italicize, and insert images but things like : 

`(html [:strong "zzzzzz"])` or
`(strong "bold me please")`
didn't work.

i'm a total clojure n00b, but would there be a way to make it easy to quickly bold and italicize text **(ideally like markdown)** without having to write a markdown parser/extension yet?  (it would take me a _long_ time to learn enough clojure to do that, as my clojure skills are currently : nil list.

**Comment by liquidz** [comment]
You can write strong tag as follows

``` clj
[:strong "bold me"]   ; html is not required
; => <strong>bold me</strong>
```

`html` function is call by misaki.core automatically.

In another way, misaki supports inline markdown with `p` function.

``` clj
(p "**bold me** or *italic me*")
; => <p class="paragraph"><strong>bold me</strong> or <em>italic me</em></p>
```
