### ISSUE TITLE
filename generating problem

### ISSUE THREAD

**Issue by liquidz** [liquidz/misaki#28]
`:post-filename-format "{{day}}.html"`

"2013-01-02-foo.html.clj" should be "02.html" but "02"

**Comment by ponkore** [comment]
おお、これは期待。微妙に不便でした…

**Comment by liquidz** [comment]
おぉ、、スミマセンでした。。
他に不便なところあったらご連絡ください！

**Comment by ponkore** [comment]
説明が不足してましたね。具体的には、misaki で post-file を `/yyyy-mm/entry/index.html` みたいな感じにしたいのです。URL 的には `http://hogehoge.github.com/yyyy-mm/entry/` みたいな感じですね。で、試しに

```
:post-filename-regexp #"(\d{4})[-_](\d{1,2})[-_](\d{1,2})[-_](.+)\.html.clj$"
:post-filename-format "{{year}}-{{month}}/{{filename}}/index.html"
```

とやってみると、`yyyy-mm/entry/index` (.html無し) が生成されたという次第です。
とりあえず

```
:post-filename-format "{{year}}-{{month}}/{{filename}}/index.html.html" ; this is dirty hack...
```

みたいな感じで今は逃げています。

[Jekyll](https://github.com/mojombo/jekyll/wiki/Permalinks) の `permalink: pretty` のような指定、もしくは post-filename-format で .html が無い場合自動的に index.html を output file として補完する、とか。

自分でも「どういう仕様が望ましいのか」がわからずに連絡せず放置してました。スミマセン。

**Comment by liquidz** [comment]
devブランチで修正しました
拡張子が消されるべきなのは foo.html.clj というパターンのみなので
cljで終わるファイル名のみ最後の拡張子を削除するようにしました。

この場合、foo.clj というファイルを出力したい場合には
foo.clj.clj としないといけませんが、cljファイルを出力することがまず無いはずなので
このような処理にしています。

**Comment by ponkore** [comment]
dev ブランチでの動作確認できました。

```
:post-filename-format "{{year}}-{{month}}/{{filename}}/index.html.clj"
```

こんな感じで `index.html` が生成されるのを確認しました。

ありがとうございます。助かります!!!

**Comment by liquidz** [comment]
あ、その場合ですと

```
:post-filename-format "{{year}}-{{month}}/{{filename}}/index.html"
```

でいけます。 .clj を付けないといけないのは気持ち悪いかと思うので

**Comment by ponkore** [comment]
なるほど。再度上記設定(.cljなし)で動くことを確認しました。ありがとうございます!!!

**Comment by liquidz** [comment]
masterにマージしたのでクローズします。
