### ISSUE TITLE
clj-growl refers clojure-1.2.0-RC1, so "lein deps" failed.

### ISSUE THREAD

**Issue by ponkore** [liquidz/misaki#29]
clj-growl が依存している jar ファイルに clojure-1.2.0-RC1 というのがあるのですが、すでに mvn , clojars 等々には存在していないようなので、ローカルの .m2/repository/ がまっさらな状態で misaki を git clone して lein deps するとエラーになります。

```
$ lein deps
Could not find artifact org.clojure:clojure:pom:1.2.0-RC1 in central (http://repo1.maven.org/maven2)
Could not find artifact org.clojure:clojure:pom:1.2.0-RC1 in clojars (https://clojars.org/repo/)
Could not find artifact org.clojure:clojure:pom:1.2.0-RC1 in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/)
Retrieving org/clojure/clojure/1.2.0-RC1/clojure-1.2.0-RC1.pom (1k)
from http://build.clojure.org/releases/
$ 
```

このことは、clj-growl の作者さん( [brentonashworth on Github ](https://github.com/brentonashworth/clj-growl) ) には Issue 1 として報告済(下手くそな英語ですが...) なのですが、最近 activity が無いようです。

なのでこの際、clj-growl は misaki から外す(説明書きを加えてオプション的位置づけにする)等の対策が必要だと思います(growl 対応は私が要望を出したので、こんなことを言うのもアレですが...)。

**Comment by liquidz** [comment]
masterにマージしたのでクローズします。
