### ISSUE TITLE
atom.xml の中の link 先が localhost:8080 を指してしまっている

### ISSUE THREAD

**Issue by ponkore** [liquidz/misaki#36]
samples/blog の中の atom.xml.clj のリンク先とか id とかが、`localhost:8080` になってしまっていて、Google Reader とかで見たときに参照先に飛べないような状態です。自分の feed だけ適当に直すという方法もなくはないのですが、せっかくなので samples/blog のものをちゃんとしたリファレンス実装にしていただけると助かります。

以下、atom.xml.clj 抜粋：

```
; @base http://localhost:8080

"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
[:feed {:xmlns "http://www.w3.org/2005/Atom"}
 [:title (:site-title site)]
 [:link {:href (str (:base site) "/atom.xml"), :rel "self"}]
 [:link {:href (:base site)}]
 [:updated (date->xml-schema (:date site))]
 [:id (:base site)]
 [:author [:name "@uochan"]]
```

**Comment by liquidz** [comment]
samples/blog についてはローカルで試しに動かすことを想定しているため
atom.xmlのid, リンクは意図的に localhost:8080 にしています。

``` clojure
; @base http://localhost:8080
```

なのでgithub pagesなどローカル以外で動かす場合には
atom.xml.clj の `@base` を適宜変更してもらうスタンスなのですが、
atom.xml.clj 内の定義だと見落としがちなので _config.clj 内に移動させるのはいかがでしょうか？

``` clojure
{
 ;; default site data
 :site { ; localhostをブログドメインに変更してもらう旨のコメント
         :atom-base "http://localhost:8080"
         }
 }
```

**Comment by ponkore** [comment]
すみません、完全に見落としてましたw   misaki の設計としては  `@base` で変更できる思想で良いと思います。
ただ、コメントいただいた `_config.clj` に書くほうが自分にとってはすっきりするので、個人的にはこちらを採用します。というわけで、この issue は close しておきます。
