### ISSUE TITLE
how to change the port 8080?

### ISSUE THREAD

**Issue by luckypoem** [liquidz/misaki#43]
hi.
u said "Access http://localhost:8080 to check sample.",but my 8080 port has been used by another app,so how to change the port 8080?

**Comment by liquidz** [comment]
You can change `:port` setting defined in _config.clj

https://github.com/liquidz/misaki/blob/master/samples/blog/_config.clj#L18

**Comment by luckypoem** [comment]
hi.
how to publish a post with source code?such as  a audio/video post?
pls see here: http://msk.brite.biz/2013-10/wether-sunshine-or-rain.html,

as3:~/misaki/samples/blog/template/posts# ls
2011-01-01-post1.html.clj   2013-10-25-test1.html.clj
2012-02-02-post2.html.clj   2013-10-25-test2.html.clj
2013-03-03-post3.html.clj   2013-10-25-test3.html.clj
2013-10-25-couple.html.clj  2013-10-25-wether-sunshine-or-rain.html.clj
as3:~/misaki/samples/blog/template/posts# cat 2013-10-25-wether-sunshine-or-rain.html.clj
; @layout post
; @title 风雨无阻
; @tag misc

#-CLJ
<embed src="http://player.youku.com/player.php/sid/XMjEzODIwODY0/v.swf" quality="high" width="500" height="400" align="middle" allowscriptaccess="sameDomain" type="application/x-shockwave-flash" /><br />虽然周华健长得有点玩世不恭，但唱的情歌还是挺不错的.
CLJ
as3:~/misaki/samples/blog/template/posts#

so how should i edit the post which is with source code?

**Comment by liquidz** [comment]
misaki's default compiler uses [hiccup](https://github.com/weavejester/hiccup), so you can write source code as follows.

``` clj
[:embed {:src "" :quality "" :width "" :height "" :align "" :allowscriptaccess "" :type ""}]
```

**Comment by luckypoem** [comment]
hi.
it's still useless.

as3:~/misaki/samples/blog/template/posts# cat 2013-10-25-wether-sunshine-or-rain.html.clj
; @layout post
; @title 风雨无阻
; @tag misc

#-CLJ
:embed {:src "http://player.youku.com/player.php/sid/XMjEzODIwODY0/v.swf" :width "500" :height "400" :type "application/x-shockwave-flash"}
虽然周华健长得有点玩世不恭，但唱的情歌还是挺不错的.
CLJ

or:
; @layout post
; @title 风雨无阻
; @tag misc

#-CLJ
[:embed {:src "http://player.youku.com/player.php/sid/XMjEzODIwODY0/v.swf" :width "500" :height "400" :type "application/x-shockwave-flash"}]
虽然周华健长得有点玩世不恭，但唱的情歌还是挺不错的.
CLJ

when u visit http://msk.brite.biz/2013-10/wether-sunshine-or-rain.html,it still cannot show the video.

**Comment by liquidz** [comment]
Please write code outside of `#-CLJ` like follows.

``` clj
; @layout post
; @title ...
; @tag misc

[:embed {:src "" :width ""}]

#-CLJ
.....
CLJ
```

**Comment by luckypoem** [comment]
this time,it's ok.tks
